runtime: python39
service: static
handlers:
# - url: /static
#   static_files: www/index.html
#   upload: www/index.html

# - url: /static/(.*)
#   static_files: www/\1
#   upload: www/(.*)

- url: /static
  static_dir: static